name : DockerImagen
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'marlon9604/prueba:nodejsimages'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
          - task: Docker@1
            displayName: Build an image
            inputs:
            containerRegistry: 'Docker Hub'
            repository: 'marlon9604/prueba'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
      