name : DockerImagen
trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  ImageName: 'marlon9604/prueba:nodejsimages'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build AND PUSH
      inputs:
        containerRegistry: 'Docker Hub'
        repository: 'marlon9604/prueba'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'

    - task: Docker@2
      inputs:
            containerRegistry: 'DockerASC'
            repository: 'Docker202102'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'